/* @proprietary license */

/** Extra search terms keyed by unprefixed docs path (locale-agnostic). */
export const DOCS_SEARCH_ALIASES: Record<string, readonly string[]> = {
  '/start/overview': [
    'what is lomi',
    'getting started',
    'introduction',
    'uemoa',
    'west africa',
    'docs home',
    'documentation',
    'welcome',
    'map',
    'task guide',
    'how do I',
    'same job',
    'rest mcp cli',
  ],
  '/start/integration-journey': [
    'quickstart',
    'first integration',
    'onboarding',
    'sandbox to live',
  ],
  '/start/create-account': [
    'sign up',
    'register',
    'create account',
    'onboarding',
    'kyc',
    'starter business',
  ],
  '/start/api-keys': [
    'api key',
    'secret key',
    'lomi_sk_test',
    'lomi_sk_live',
    'sandbox key',
    'x-api-key',
    'LOMI_SECRET_KEY',
    'bearer',
  ],
  '/start/first-payment': ['test payment', 'hello world', 'try checkout'],
  '/start/sandbox-payments': [
    'test card',
    'sandbox',
    'wave sandbox',
    'mtn sandbox',
    'simulate',
  ],
  '/start/go-live': ['go live', 'production', 'live keys', 'launch'],
  '/build/accept/checkout': [
    'hosted checkout',
    'checkout session',
    'checkout_url',
    'redirect',
    'one-off',
    'one off payment',
    'collect money',
    'hosted checkout task',
  ],
  '/build/accept/payment-links': ['payment link', 'shareable link', 'invoice link'],
  '/build/payment-channels': [
    'payment methods',
    'rails',
    'wave',
    'mtn',
    'momo',
    'cards',
    'spi',
    'pi-spi',
  ],
  '/build/payment-methods/mtn-momo': [
    'momo',
    'mtn',
    'mobile money',
    'ussd',
    'mtn momo',
  ],
  '/build/payment-methods/wave': ['wave', 'qr', 'senegal'],
  '/build/payment-methods/cards': [
    '3ds',
    '3d secure',
    'visa',
    'mastercard',
    'stripe',
    'gim',
  ],
  '/build/mobile-money': [
    'momo',
    'om',
    'orange money',
    'wave',
    'mtn',
    'async',
    'ussd',
  ],
  '/build/reliability': [
    'webhook',
    'webhook secret',
    'signature',
    'hmac',
    'callback',
    'events',
  ],
  '/build/reliability/handling-webhooks': [
    'webhook',
    'signature',
    'raw body',
    'verify',
  ],
  '/build/money/refunds': [
    'refund',
    'partial refund',
    'chargeback',
    'refund task',
    'chargeback task',
    'dispute task',
  ],
  '/build/money/disputes': ['dispute', 'chargeback', 'representment'],
  '/build/money/payouts': [
    'payout',
    'withdrawal',
    'settlement',
    'beneficiary',
    'withdraw',
    'seller payout',
    'beneficiary task',
  ],
  '/build/money/balance-and-settlement': [
    'settlement',
    'balance',
    'available',
    'pending',
    'f cfa',
    'xof',
    'reconcile',
    'settlement period',
    'available_at',
  ],
  '/build/billing/subscriptions': [
    'recurring',
    'billing',
    'monthly',
    'plan',
    'monthly billing',
    'recurring task',
    'saas plan',
  ],
  '/build/billing/usage-billing': [
    'meter',
    'usage',
    'credits',
    'entitlement',
    'metered',
    'usage task',
    'api calls billing',
  ],
  '/build/mcp': ['mcp', 'cursor', 'claude', 'agent', 'model context'],
  '/api/authentication': [
    'auth',
    'x-api-key',
    'sandbox',
    'live',
    'environment',
  ],
  '/api/errors': ['401', '404', '429', 'rate limit', 'idempotency'],
  '/api/index': ['centimes', 'minor units', 'amount', 'currency_code'],
  '/build/reliability/payment-lifecycle': [
    'status',
    'pending',
    'completed',
    'failed',
    'held',
    'expired',
    'refunded',
  ],
  '/start/merchant-of-record/pricing': [
    'fees',
    'pricing',
    '2.9%',
    'f cfa',
    'volume',
    'tier',
  ],
  '/start/support': ['help', 'contact', 'email', 'discord'],
  '/build/reliability/security-best-practices': [
    'vulnerability',
    'disclosure',
    'security.txt',
    'bug bounty',
    'report',
  ],
};

/** Empty-state search rows: page titles, not route paths. */
export const DOCS_SEARCH_SUGGESTED = [
  {
    href: '/start/overview',
    title: { en: 'What is lomi.?', fr: "Qu'est-ce que lomi. ?" },
  },
  {
    href: '/start/create-account',
    title: {
      en: 'How do I create an account?',
      fr: 'Comment créer un compte ?',
    },
  },
  {
    href: '/start/api-keys',
    title: { en: 'Where are my API keys?', fr: 'Où trouver mes clés API ?' },
  },
  {
    href: '/start/first-payment',
    title: {
      en: 'How do I test a payment?',
      fr: 'Comment tester un paiement ?',
    },
  },
  {
    href: '/build/accept/checkout',
    title: { en: 'How do I use checkout?', fr: 'Comment utiliser le checkout ?' },
  },
] as const;

export const DOCS_SEARCH_SUGGESTED_HREFS = DOCS_SEARCH_SUGGESTED.map(
  (item) => item.href,
);

export function aliasesForPath(path: string): readonly string[] {
  const normalized = path.startsWith('/') ? path : `/${path}`;
  return DOCS_SEARCH_ALIASES[normalized] ?? [];
}
