export interface APIResourceConfig {
  tableName: string;
  path?: string;
  displayName?: string;
  idField?: string;
  enabled: boolean;
  operations?: {
    list?: boolean;
    get?: boolean;
    create?: boolean;
    update?: boolean;
    delete?: boolean;
  };
  tag?: string;
  description?: string;
}

export const API_RESOURCES: APIResourceConfig[] = [
  {
    tableName: 'accounts',
    enabled: true,
    tag: 'Accounts',
    idField: 'account_id',
    description:
      'Account balances - view organization account balances and SPI account information',
    operations: {
      list: true,
      get: true,
      create: false, // Accounts are system-managed
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'organizations',
    enabled: true,
    tag: 'Organizations',
    idField: 'organization_id',
    description:
      'Organization metrics - view MRR, ARR, total revenue, merchant lifetime value, and other organization metrics',
    operations: {
      list: true,
      get: true,
      create: false, // Organizations are system-managed
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'merchants',
    path: 'merchants',
    enabled: true,
    tag: 'Merchants',
    idField: 'merchant_id',
    description:
      'Merchant profile and cached organization metrics (MRR, ARR, LTV, balance)',
    operations: {
      list: false,
      get: true,
      create: false,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'customers',
    enabled: true,
    tag: 'Customers',
    description: 'Customer management - create and manage customer profiles',
    operations: {
      list: true,
      get: true,
      create: true,
      update: true,
      delete: true,
    },
  },
  {
    tableName: 'payment_requests',
    enabled: true,
    tag: 'Payment Requests',
    idField: 'request_id',
    description: 'Payment requests - create payment intents and track status',
    operations: {
      list: true,
      get: true,
      create: true,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'transactions',
    enabled: true,
    tag: 'Transactions',
    idField: 'transaction_id',
    description:
      'Transaction history - view completed and pending transactions',
    operations: {
      list: true,
      get: true,
      create: false, // Transactions are created by the system, not by merchants
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'refunds',
    enabled: true,
    tag: 'Refunds',
    idField: 'refund_id',
    description: 'Refund management - process and track refunds',
    operations: {
      list: true,
      get: true,
      create: true,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'products',
    enabled: true,
    tag: 'Products',
    idField: 'product_id',
    description: 'Products - manage one-time and recurring products',
    operations: {
      list: true,
      get: true,
      create: true,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'subscriptions',
    enabled: true,
    tag: 'Subscriptions',
    idField: 'subscription_id',
    description:
      'Subscription management - create and manage recurring billing',
    operations: {
      list: true,
      get: true,
      create: false,
      update: true,
      delete: false,
    },
  },
  {
    tableName: 'discount_coupons',
    enabled: true,
    tag: 'Discount Coupons',
    idField: 'coupon_id',
    description: 'Discount coupons - create and manage promotional codes',
    operations: {
      list: true,
      get: true,
      create: true,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'checkout_sessions',
    enabled: true,
    tag: 'Checkout Sessions',
    idField: 'checkout_session_id',
    description: 'Checkout sessions - create hosted payment pages',
    operations: {
      list: true,
      get: true,
      create: true,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'payment_links',
    enabled: true,
    tag: 'Payment Links',
    idField: 'link_id',
    description: 'Payment links - shareable payment URLs',
    operations: {
      list: true,
      get: true,
      create: true,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'payouts',
    enabled: true,
    tag: 'Payouts',
    idField: 'payout_id',
    description: 'Payout management - transfer funds to beneficiaries',
    operations: {
      list: true,
      get: true,
      create: true,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'beneficiary_payouts',
    enabled: true,
    tag: 'Beneficiary Payouts',
    idField: 'payout_id',
    description: 'Beneficiary payouts - track individual payout transfers',
    operations: {
      list: true,
      get: true,
      create: true,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'providers',
    path: 'providers',
    enabled: true,
    tag: 'Providers',
    description: 'Payment provider connection status for the organization',
    operations: {
      list: true,
      get: false,
      create: false,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'webhooks',
    enabled: true,
    tag: 'Webhooks',
    idField: 'webhook_id',
    description:
      'Webhook configuration - receive real-time event notifications',
    operations: {
      list: true,
      get: true,
      create: true,
      update: true,
      delete: true,
    },
  },
  {
    tableName: 'webhook_delivery_logs',
    enabled: true,
    tag: 'Webhook Delivery Logs',
    idField: 'log_id',
    description: 'Webhook event log - history of webhook deliveries',
    operations: {
      list: true,
      get: true,
      create: false, // Logs are system-generated
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'api_interactions',
    enabled: true,
    tag: 'API Interactions',
    idField: 'interaction_id',
    description: 'Merchant API request and response audit trail',
    operations: {
      list: false,
      get: false,
      create: false,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'api_error_logs',
    enabled: true,
    tag: 'API Error Logs',
    idField: 'error_id',
    description: 'Merchant API error log entries',
    operations: {
      list: false,
      get: false,
      create: false,
      update: false,
      delete: false,
    },
  },
  {
    tableName: 'webhook_delivery_attempts',
    enabled: true,
    tag: 'Webhook Delivery Attempts',
    idField: 'attempt_id',
    description: 'Per-HTTP-attempt webhook delivery history',
    operations: {
      list: false,
      get: false,
      create: false,
      update: false,
      delete: false,
    },
  },
];

export function getEnabledResources(): APIResourceConfig[] {
  return API_RESOURCES.filter((r) => r.enabled);
}

/**
 * Enum names that should be exposed in the API types
 * These enums will be included in the generated api.ts file
 */
export const EXPOSED_ENUMS = [
  'currency_code',
  'payment_method_code',
  'provider_code',
  'provider_payment_status',
  'transaction_status',
  'transaction_type',
  'refund_status',
  'payout_status',
  'subscription_status',
  'product_type',
  'pricing_model',
  'usage_frequency',
  'checkout_session_status',
  'invoice_status',
  'webhook_event',
  'spi_payment_status',
  'spi_account_status',
  'spi_account_type',
  'spi_payment_category',
  'spi_payment_flow_type',
  'spi_payment_request_category',
  'spi_document_type',
  'spi_rejection_reason',
  'spi_webhook_event_code',
  'organization_status',
  'organization_verification_status',
  'pricing_plan_type',
  'fee_category',
  'fee_subcategory',
  'billing_interval',
  'customer_type',
  'discount_type',
  'qr_code_type',
  'link_type',
  'failed_payment_action',
  'first_payment_type',
  'usage_aggregation',
  'integration_source',
  'onboarding_status',
  'event_type',
  'event_category',
  'event_severity',
  'event_processing_status',
  'product_fulfillment_type',
  'dispute_status',
  'billing_period_status',
  'spi_alias_type',
  'network_enrollment_status',
  'network_membership_status',
  'network_fee_entry_status',
  'network_fee_entry_type',
  'network_transfer_status',
  'network_transfer_type',
  'network_fee_rule_status',
  'network_operator_fee_type',
  'network_capability_status',
  'radar_decision',
  'radar_mode',
  'radar_rail',
  'radar_signal_provider',
  'platform_partner_status',
  'provisioning_key_kind',
  'kyc_status',
];

/**
 * Check if an enum should be exposed
 */
export function isEnumExposed(enumName: string): boolean {
  return EXPOSED_ENUMS.includes(enumName);
}

/**
 * RPC function names that should be exposed in the API types
 * These functions will be included in the generated api.ts file
 */
export const EXPOSED_FUNCTIONS = [
  // Auth, guards & idempotency
  'lookup_api_idempotency_record',
  'record_api_idempotency_record',
  'resolve_network_request_context',
  'verify_api_key',
  'verify_api_key_context',
  'verify_dashboard_org_access',
  'verify_partner_management_key',
  'verify_provisioning_key',
  'verify_provisioning_merchant_access',

  // API logging & telemetry
  'fetch_logs',
  'get_activity_log',
  'get_api_error_log',
  'get_api_error_logs',
  'get_api_request_log',
  'get_api_request_logs',
  'log_api_error',
  'log_api_interaction',
  'log_api_interaction_context',
  'log_wide_event',

  // Accounts & organizations
  'check_merchant_available_balance',
  'fetch_account_balance',
  'fetch_balance_breakdown',
  'fetch_organization_details',
  'get_account',
  'get_merchant_arr',
  'get_merchant_balance',
  'get_merchant_details',
  'get_merchant_from_organization',
  'get_merchant_mrr',
  'list_accounts',
  'list_organizations',

  // Customers & portal
  'complete_customer_portal_payment_method_setup',
  'create_customer',
  'create_customer_portal_launch_session',
  'create_or_update_customer',
  'customer_portal_list_payment_methods',
  'customer_portal_list_subscriptions',
  'customer_portal_list_transactions',
  'customer_portal_manage_subscription',
  'customer_portal_set_default_payment_method',
  'customer_portal_validate_session',
  'delete_customer',
  'fetch_customer_transactions',
  'fetch_customers',
  'fetch_customers_with_status',
  'get_customer',
  'get_customer_by_organization',
  'get_customer_invoice_api',
  'get_customer_spi_alias',
  'get_customer_subscription',
  'merchant_list_customer_portal_audit_events',
  'update_customer',
  'update_customer_invoice_api',
  'update_customer_metadata',
  'update_customer_subscription',

  // Checkout sessions & catalog
  'create_checkout_session',
  'create_checkout_session_with_line_items',
  'get_checkout_session_api',
  'get_checkout_session_by_wave_id',
  'list_checkout_sessions',
  'resolve_checkout_catalog_amount',

  // Invoices
  'create_invoice_checkout_session',
  'create_invoice_receivable',
  'get_blocking_customer_obligations',
  'list_customer_invoices_api',

  // Payment links & requests
  'create_payment_link',
  'create_payment_request_api',
  'get_payment_link_api',
  'get_payment_request_api',
  'list_payment_links',
  'list_payment_requests',

  // Products & coupons
  'create_discount_coupon',
  'create_price',
  'create_product',
  'fetch_products',
  'get_coupon_details_for_management',
  'get_coupon_performance',
  'get_organization_coupons',
  'get_price_api',
  'get_product_api',
  'get_product_fees_api',
  'get_product_prices_api',
  'set_default_price',

  // Subscriptions
  'build_merchant_subscription_webhook_payload',
  'calculate_renewal_charge_amount',
  'cancel_customer_subscription',
  'complete_stripe_deferred_subscription_setup',
  'fallback_subscription_renewal_to_manual_checkout',
  'fetch_subscriptions',
  'fetch_subscriptions_for_customer',
  'finalize_subscription_renewal_after_retries',
  'get_active_subscriptions_for_renewal',
  'handle_subscription_renewal_payment_failure',
  'manage_subscription',
  'record_subscription_renewal',
  'subscription_renewal_already_processed',

  // Transactions, charges & refunds
  'apply_mtn_partial_refund_charges',
  'apply_stripe_dispute_lost_effects',
  'apply_wave_partial_refund_charges',
  'create_manual_refund_request_api',
  'create_mtn_refund_request_api',
  'create_mtn_transaction',
  'create_refund',
  'create_stripe_card_refund',
  'create_stripe_card_refund_api',
  'create_stripe_transaction',
  'create_wave_refund_request_api',
  'evaluate_radar_for_charge',
  'fetch_transactions',
  'get_effective_other_fee_config',
  'get_mtn_transaction_by_external_id',
  'get_mtn_transaction_by_reference_id',
  'get_refund',
  'get_stripe_provider_charge_id',
  'get_transaction',
  'get_transaction_by_stripe_intent',
  'handle_stripe_dispute_created',
  'handle_stripe_dispute_updated',
  'handle_stripe_refund',
  'list_refunds',
  'merge_stripe_radar_signals',
  'prepare_stripe_payment_amount',
  'rollback_mtn_refund',
  'rollback_wave_refund',
  'transaction_has_pending_dispute',
  'update_balances_for_transaction',
  'update_mtn_provider_reference',
  'update_organization_balance_for_refund',
  'update_stripe_checkout_status',
  'update_transaction_fee_metadata',
  'update_transaction_status',

  // Payouts & settlements
  'create_beneficiary_payout',
  'fetch_beneficiary_payouts',
  'fetch_payout_method_details',
  'fetch_payouts',
  'fetch_settlement_periods',
  'fetch_settlement_transactions',
  'fetch_wave_provider_settings',
  'get_beneficiary_payout_api',
  'get_payout_api',
  'get_payout_details',
  'initiate_spi_payout',
  'initiate_withdrawal_api',
  'update_spi_payout_status',

  // Providers & webhooks
  'claim_inbound_provider_webhook_event',
  'create_webhook',
  'delete_webhook',
  'fetch_organization_providers_settings_api',
  'fetch_organization_webhooks',
  'find_wave_transaction_by_provider_txn_id',
  'get_wave_transaction_by_checkout_id',
  'get_webhook',
  'get_webhook_by_id',
  'get_webhook_delivery_log',
  'get_webhook_delivery_log_with_attempts',
  'get_webhook_delivery_logs',
  'get_webhook_delivery_logs_with_attempts',
  'log_webhook_delivery',
  'mark_webhook_dispatch_dead_letter',
  'mark_webhook_dispatch_delivered',
  'record_webhook_delivery_attempt',
  'recover_missing_wave_transaction',
  'update_webhook',
  'update_webhook_delivery_status',
  'webhook_dispatch_ensure',
  'webhook_dispatch_should_process',
  'webhook_outbox_upsert_event',

  // SPI
  'complete_spi_payment',
  'create_spi_account_alias',
  'fail_spi_payout',
  'finalize_invoice_spi_rtp_initiated',
  'finalize_pos_spi_payment_initiated',
  'get_checkout_spi_payment_status',
  'get_invoice_spi_payment_status',
  'get_pos_spi_payment_status',
  'get_spi_account_alias',
  'get_spi_account_number',
  'get_spi_account_snapshot',
  'get_spi_payout_method_destination',
  'get_spi_provider_connection',
  'get_spi_provider_metadata',
  'list_orgs_missing_spi_account',
  'list_spi_accounts_for_balance_sync',
  'prepare_checkout_spi_payment',
  'prepare_invoice_spi_rtp',
  'prepare_pos_spi_payment',
  'provision_spi_account',
  'update_spi_account_balance',

  // GIM
  'create_gim_transaction',
  'finalize_gim_payment',
  'prepare_checkout_gim_payment',

  // Network
  'calculate_network_operator_fee',
  'create_network_account_session',
  'create_network_enrollment_session',
  'create_network_transfer_for_api',
  'enqueue_network_webhook_event',
  'fetch_network_balance_for_api',
  'fetch_network_customer_transactions_for_api',
  'fetch_network_customers',
  'fetch_network_customers_for_api',
  'fetch_network_enrollments',
  'fetch_network_member_balance',
  'fetch_network_members',
  'fetch_network_operator_fee_entries',
  'fetch_network_operator_fee_rules',
  'fetch_network_organization_context',
  'fetch_network_provider_settings_for_api',
  'fetch_network_refunds_for_api',
  'fetch_network_transactions',
  'fetch_network_transactions_for_api',
  'fetch_network_transfers',
  'fetch_network_transfers_for_api',
  'get_network_customer_for_api',
  'get_network_membership_operator_fee_rule_id',
  'get_network_operator_fee_entry_summary',
  'get_network_refund_for_api',
  'get_network_transaction_for_api',
  'get_network_transfer_for_api',
  'get_network_webhook_enrichment',
  'move_network_funds',
  'network_member_health',
  'record_network_login_link',
  'record_network_operator_fee_entry',
  'record_network_operator_fee_reversal',
  'record_network_transaction_context',
  'request_network_operator_live',
  'resolve_network_account_session',
  'resolve_network_member_merchant_id',
  'reverse_network_transfer_for_api',
  'set_network_capability_grant',
  'set_network_membership_fee_rule',
  'set_network_membership_status',
  'set_network_operator_default_fee_rule',
  'settle_network_refund',
  'settle_network_transaction',
  'setup_network_operator_profile',
  'update_network_operator_profile',
  'upsert_network_customer_metadata_for_api',
  'upsert_network_operator_fee_rule',

  // Metering & usage
  'check_entitlement',
  'create_entitlement',
  'create_meter',
  'create_usage_subscription',
  'credit_usage_wallet',
  'enqueue_usage_event',
  'fetch_combined_revenue_metrics',
  'get_meter_api',
  'get_meter_balance_api',
  'get_partner_usage_summary',
  'get_subscription_usage_api',
  'get_usage_event_api',
  'list_billing_periods_api',
  'list_meters_api',
  'list_stale_pending_usage_events',
  'list_usage_events_api',
  'process_usage_billing_cycle',
  'process_usage_event',
  'process_usage_invoice_dunning',
  'update_meter_api',

  // Radar & disputes
  'fetch_disputes',
  'fetch_risk_assessments',
  'get_dispute_api',
  'get_dispute_by_stripe_id',
  'get_dispute_webhook_payload',
  'get_organization_radar_settings_api',
  'get_risk_assessment_api',
  'update_organization_radar_settings_api',

  // Agent
  'create_agent_event_subscription',
  'create_agent_handoff',
  'create_agent_workflow_run',
  'delete_agent_event_subscription',
  'get_agent_event_subscription',
  'get_agent_handoff',
  'get_agent_workflow_run',
  'list_agent_event_subscriptions',
  'update_agent_workflow_run_step',

  // OAuth
  'oauth_create_authorization_code',
  'oauth_exchange_authorization_code',
  'oauth_get_client',
  'oauth_introspect_token',
  'oauth_mint_merchant_connection_key',
  'oauth_refresh_access_token',
  'oauth_register_client',
  'oauth_revoke_token',
  'oauth_verify_client_secret',

  // Partner & provisioning
  'check_provisioning_daily_quota',
  'complete_onboarding',
  'get_active_merchant_organization',
  'get_active_partner_provisioning_key',
  'get_live_activation_status',
  'get_or_create_self_service_partner',
  'get_organization_kyc_status',
  'increment_provisioning_daily_usage',
  'log_provisioning_audit',
  'partner_list_provisioning_keys',
  'partner_mint_provisioning_key',
  'partner_revoke_provisioning_key',
  'provisioning_fetch_api_keys',
  'provisioning_get_onboarding_status',
  'provisioning_link_organization',
  'register_provisioning_merchant_account',
  'request_live_activation',

  // Other
  'complete_mtn_refund_provider',
  'fetch_pending_webhook_outbox_jobs',
  'get_organization_uemoa_country_code',
  'list_customer_subscriptions',
];

/**
 * Check if a function should be exposed
 */
export function isFunctionExposed(functionName: string): boolean {
  return EXPOSED_FUNCTIONS.includes(functionName);
}
